/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import dao.ParticipantsDao;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Blob;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.mail.MessagingException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import main.Gmail;
import pojo.JobPojo;
import pojo.ParticipantsPojo;

/**
 *
 * @author Neel_Esh
 */
public class HrViewProfileFrame extends javax.swing.JFrame {

    /** Creates new form HrViewProflieFrame1 */
    String jobId;
    public HrViewProfileFrame()
    {
        initComponents();
    }
    
    public HrViewProfileFrame(String pid,String jobId) 
    {
        initComponents();
        this.jobId=jobId;
        this.setLocationRelativeTo(null);
        try
        {
            ResultSet rs = ParticipantsDao.getParticipantsProfile(pid);
            if(rs.next())
            {
                pIdLbl.setText(rs.getString(1));
                txtMail.setText(rs.getString(2));
                txtName.setText(rs.getString(3));
                txtPhone.setText(rs.getString(4));
                String[] tags=rs.getString(5).split(",");
                skill1Txt.setText(tags[0]);
                skill2Txt.setText(tags[1]);
                skill3Txt.setText(tags[2]);
                skill4Txt.setText(tags[3]);
                qualificationTxt.setText(rs.getString(6));
            }
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,"DB-error while Loading data","Error",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
        this.setVisible(true);
    }

    void sendMail(ParticipantsPojo pj,JobPojo jb)
    {
        Runnable r1=()->{
            try
            {
                Gmail gmail = new Gmail();
                gmail.interviewInvition(pj,jb);
                gmail.sendEmail();
            }
            catch(MessagingException ex)
            {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null,"Error while sending E-mail");
            }
            
        };          
        Thread th1=new Thread(r1);
        th1.start();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pIdLbl = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtPhone = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        skill1Txt = new javax.swing.JTextField();
        skill3Txt = new javax.swing.JTextField();
        skill4Txt = new javax.swing.JTextField();
        qualificationTxt = new javax.swing.JTextField();
        DipperSeperator2 = new javax.swing.JSeparator();
        downloadResumeBtn = new javax.swing.JButton();
        sendMailBtn = new javax.swing.JButton();
        DipperSeperator4 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        skill2Txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(243, 246, 254));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.setEditable(false);
        txtName.setBackground(new java.awt.Color(173, 192, 234));
        txtName.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        txtName.setBorder(null);
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 315, 410, 30));

        txtMail.setEditable(false);
        txtMail.setBackground(new java.awt.Color(173, 192, 234));
        txtMail.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        txtMail.setBorder(null);
        jPanel1.add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 455, 410, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 450, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 450, 40));

        jLabel6.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        jLabel6.setText("Email :-");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));

        pIdLbl.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        pIdLbl.setText("P-101");
        jPanel1.add(pIdLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 280, -1));

        jLabel15.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        jLabel15.setText("Qualification :-");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, -1, -1));

        jLabel19.setFont(new java.awt.Font("Heiti SC", 0, 18)); // NOI18N
        jLabel19.setText("Name :-");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 420, 10));

        jLabel21.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        jLabel21.setText("Participant id :");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 200));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 970, 10));

        txtPhone.setEditable(false);
        txtPhone.setBackground(new java.awt.Color(173, 192, 234));
        txtPhone.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        txtPhone.setBorder(null);
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 385, 410, 30));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 450, 40));

        jLabel23.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        jLabel23.setText("Mobile no :-");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        skill1Txt.setEditable(false);
        skill1Txt.setBackground(new java.awt.Color(173, 192, 234));
        skill1Txt.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        skill1Txt.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.gray));
        jPanel1.add(skill1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 190, 30));

        skill3Txt.setEditable(false);
        skill3Txt.setBackground(new java.awt.Color(173, 192, 234));
        skill3Txt.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        skill3Txt.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.gray));
        jPanel1.add(skill3Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, 190, 30));

        skill4Txt.setEditable(false);
        skill4Txt.setBackground(new java.awt.Color(173, 192, 234));
        skill4Txt.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        skill4Txt.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.gray));
        jPanel1.add(skill4Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 540, 190, 30));

        qualificationTxt.setEditable(false);
        qualificationTxt.setBackground(new java.awt.Color(173, 192, 234));
        qualificationTxt.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        qualificationTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.gray));
        jPanel1.add(qualificationTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 970, 30));
        jPanel1.add(DipperSeperator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, 970, 20));

        downloadResumeBtn.setBackground(new java.awt.Color(173, 192, 234));
        downloadResumeBtn.setText("Download Resume");
        downloadResumeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadResumeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(downloadResumeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 220, 30));

        sendMailBtn.setBackground(new java.awt.Color(173, 192, 234));
        sendMailBtn.setText("Send Mail");
        sendMailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMailBtnActionPerformed(evt);
            }
        });
        jPanel1.add(sendMailBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 680, 290, 30));
        jPanel1.add(DipperSeperator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 970, 20));

        jLabel18.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        jLabel18.setText("Skills -");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, -1, -1));

        skill2Txt.setEditable(false);
        skill2Txt.setBackground(new java.awt.Color(173, 192, 234));
        skill2Txt.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        skill2Txt.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.gray));
        jPanel1.add(skill2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 190, 30));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/World-Map.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 970, 200));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/transparent logo.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new/viewAllQualified.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 170, 170));

        backBtn.setBackground(new java.awt.Color(173, 192, 234));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 680, 290, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void downloadResumeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadResumeBtnActionPerformed
        // TODO add your handling code here:
        File file;
        JFileChooser chooser=new JFileChooser();
        
        chooser.setDialogTitle("Choose Directory for downlaod");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        int result =chooser.showDialog(null,"Choose");
        
        if (result == chooser.APPROVE_OPTION) 
        {   
            file=chooser.getSelectedFile();
            try
            {
                Blob b=ParticipantsDao.getParticipantsResume(pIdLbl.getText().trim());
                byte []arr=b.getBytes(1,(int)b.length());
                FileOutputStream output=new FileOutputStream(file.toString()+"/"+txtName.getText()+".pdf");
                output.write(arr);
                
                JOptionPane.showMessageDialog(null,"File Downloaded and saved SuccessFully !!!","Success",JOptionPane.INFORMATION_MESSAGE);
                
            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null,"DB-error while Loading data","Error",JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
            catch(FileNotFoundException ex)
            {
                JOptionPane.showMessageDialog(null,"File not found","Error",JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
            catch(IOException ex)
            {
                JOptionPane.showMessageDialog(null,"IO error","Error",JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
            
        } 
        else if (result == chooser.CANCEL_OPTION) 
        {
            System.out.println("Cancel was selected");
        }  
    }//GEN-LAST:event_downloadResumeBtnActionPerformed

    private void sendMailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMailBtnActionPerformed
        // TODO add your handling code here:
        try
        {
            ParticipantsPojo pj=new ParticipantsPojo();
            pj.setpId(pIdLbl.getText().trim());
            pj.setName(txtName.getText().trim());
            pj.setUserId(txtMail.getText().trim());
            ResultSet rs = dao.JobDao.getJobDetailsByJobId(jobId);
            JobPojo jb=new JobPojo();
            if(rs.next())
            {
                jb.setJobId(rs.getString(1));
                jb.setJobTitle(rs.getString(2));
                jb.setHrId(rs.getString(3));            
            }
            sendMail(pj,jb);
            JOptionPane.showMessageDialog(null,"Mail Sended SuccessFully","Success",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,"DB-error while Loading data","Error",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_sendMailBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        new HrViewAllQualifiedParticipantsFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HrViewProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HrViewProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HrViewProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HrViewProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HrViewProfileFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator DipperSeperator2;
    private javax.swing.JSeparator DipperSeperator4;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton downloadResumeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel pIdLbl;
    private javax.swing.JTextField qualificationTxt;
    private javax.swing.JButton sendMailBtn;
    private javax.swing.JTextField skill1Txt;
    private javax.swing.JTextField skill2Txt;
    private javax.swing.JTextField skill3Txt;
    private javax.swing.JTextField skill4Txt;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables

}
