/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.HrDao;
import dao.JobDao;
import dao.ParticipantsDao;
import dao.ResultsDao;
import pojo.CurrentUser;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 *@author Neel_Esh
 */
public class HrViewAllQualifiedParticipantsFrame extends javax.swing.JFrame {

    /**
     * Creates new form ViewAllQualifiedParticipantsFrame
     */
    int per=4;
    String companyName;
    DefaultTableModel model;
   
    public HrViewAllQualifiedParticipantsFrame() {
        initComponents();
        model=(DefaultTableModel)allPtTbl.getModel();
        this.setLocationRelativeTo(null);
        nameLbl.setText(CurrentUser.name);
        setJobIdJCbx();
        insertData();
        
    }
    
    void setJobIdJCbx()
    {
        try
        {   
            companyName=HrDao.getCompanyNameById(CurrentUser.id.trim());
            ResultSet rs=JobDao.getAllOpenJobByCompanyName(companyName);
            int i=0;
            jobIdJcbox.removeAllItems();
            while(rs.next())
            {
                jobIdJcbox.insertItemAt(rs.getString(1),i);
                i++;
            }
            jobIdJcbox.setSelectedIndex(0);
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,"DB-error while Loading data","Error",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
        
    }
    
    void insertData()
    {
        try
        {
            int ii=0;
            ResultSet rs=ResultsDao.getAllQualifiedParticipantIdByCompanyName(companyName,per,(String)jobIdJcbox.getSelectedItem());
            while(rs.next())
            {
                ResultSet rs1=ParticipantsDao.viewParticipantsById1(rs.getString(1));
                int flag=0;
                for(int i=ii;rs1.next();i++)
                {   
                    ii++;
                    flag=flag+1;
                    for(int j=0;j<4;j++)
                    {
                        allPtTbl.setValueAt(rs1.getString(j+1),i,j);
                    }
                }
                if(flag==0)
                {
                    JOptionPane.showMessageDialog(null,"No one applied for your company yet !!!","SomeThing Went Wrong ",JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }    
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,"DB-error while Loading data","Error",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
    
    int getJCBResult()
    {
        if(perJCBx.getSelectedIndex()==0)
            return 5;
        else if(perJCBx.getSelectedIndex()==1)
            return 49;
        else
            return 74;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        viewProfileBtn = new javax.swing.JButton();
        nameLbl = new javax.swing.JLabel();
        UpperSeperator = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        logOutBtn = new javax.swing.JButton();
        AddNewHrLBL = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameLbl1 = new javax.swing.JLabel();
        DipperSeperator = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jobIdJcbox = new javax.swing.JComboBox<>();
        backBtn1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        allPtTbl = new javax.swing.JTable();
        perJCBx = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 246, 254));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewProfileBtn.setBackground(new java.awt.Color(173, 192, 234));
        viewProfileBtn.setText("View Profile");
        viewProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProfileBtnActionPerformed(evt);
            }
        });
        jPanel1.add(viewProfileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 670, 340, -1));

        nameLbl.setFont(new java.awt.Font("Noteworthy", 1, 24)); // NOI18N
        nameLbl.setText("Neelesh");
        jPanel1.add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 265, 190, 40));
        jPanel1.add(UpperSeperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 970, 10));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 200));

        logOutBtn.setBackground(new java.awt.Color(173, 192, 234));
        logOutBtn.setText("Logout");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(logOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 670, 160, -1));

        AddNewHrLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddNewHrLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new/viewAllQualified.png"))); // NOI18N
        AddNewHrLBL.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(AddNewHrLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 210, 220));

        jLabel4.setFont(new java.awt.Font("Noteworthy", 1, 24)); // NOI18N
        jLabel4.setText("Welcome , ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 265, 110, 40));

        nameLbl1.setFont(new java.awt.Font("Noteworthy", 1, 18)); // NOI18N
        nameLbl1.setText("All Participants Applied for Job -");
        jPanel1.add(nameLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 280, 30));
        jPanel1.add(DipperSeperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 1030, 20));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/World-Map.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 970, 200));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/transparent logo.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, -1));

        jobIdJcbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "<50%", "<75%" }));
        jobIdJcbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobIdJcboxActionPerformed(evt);
            }
        });
        jPanel1.add(jobIdJcbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, 130, -1));

        backBtn1.setBackground(new java.awt.Color(173, 192, 234));
        backBtn1.setText("Back");
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 160, -1));

        allPtTbl.setBackground(new java.awt.Color(173, 192, 234));
        allPtTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Participants Id", "Name", "Skills", "Qualifications"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        allPtTbl.setShowGrid(true);
        allPtTbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(allPtTbl);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 740, 230));

        perJCBx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "<50%", "<75%" }));
        perJCBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perJCBxActionPerformed(evt);
            }
        });
        jPanel1.add(perJCBx, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 360, 130, -1));

        jLabel1.setText("Percent <");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 340, -1, -1));

        jLabel2.setText("Job Id");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProfileBtnActionPerformed
        // TODO add your handling code here:
        String jobId=(String)jobIdJcbox.getSelectedItem().toString().trim();
        int row=allPtTbl.getSelectedRow();
        if(row>-1)
        {
           String ptId=(String)allPtTbl.getValueAt(row,0);
           new HrViewProfileFrame(ptId,jobId).setVisible(true);
           this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"No row selected","Warning",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_viewProfileBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed
        // TODO add your handling code here:
        new HrOptionFrame().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_backBtn1ActionPerformed

    private void jobIdJcboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobIdJcboxActionPerformed
        // TODO add your handling code here:
        per=getJCBResult();
        model.setRowCount(0);
        model.setRowCount(13);
        
        insertData();
    }//GEN-LAST:event_jobIdJcboxActionPerformed

    private void perJCBxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perJCBxActionPerformed
        // TODO add your handling code here:
        per=getJCBResult();
        model.setRowCount(0);
        model.setRowCount(13);
        
        insertData();
    }//GEN-LAST:event_perJCBxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HrViewAllQualifiedParticipantsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HrViewAllQualifiedParticipantsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HrViewAllQualifiedParticipantsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HrViewAllQualifiedParticipantsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HrViewAllQualifiedParticipantsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddNewHrLBL;
    private javax.swing.JSeparator DipperSeperator;
    private javax.swing.JSeparator UpperSeperator;
    private javax.swing.JTable allPtTbl;
    private javax.swing.JButton backBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> jobIdJcbox;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel nameLbl1;
    private javax.swing.JComboBox<String> perJCBx;
    private javax.swing.JButton viewProfileBtn;
    // End of variables declaration//GEN-END:variables
}
