/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.ParticipantsDao;
import pojo.CurrentUser;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Neel_Esh
 */
public class PtEditProfileFrame extends javax.swing.JFrame {

    /**
     * Creates new form PtEditProfileFrame
     */
    private File file;
    public PtEditProfileFrame() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        pwdPanel.setVisible(false);
        resumePanel.setVisible(false);
        insertData();
    }
    
    void insertData()
    {
        try
        {
            ResultSet rs=ParticipantsDao.viewParticipantsById(CurrentUser.id);
            if(rs.next())
            {
                mailTxt.setText(rs.getString(2));
                nameTxt.setText(rs.getString(3));
                phnTxt.setText(rs.getString(4));
            }
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,"DB-error while Loading data","Error",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        resumePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        FilePathTxt = new javax.swing.JTextField();
        BrowseFileBtn = new javax.swing.JButton();
        PhnLbl3 = new javax.swing.JLabel();
        resumeCheckBox = new javax.swing.JCheckBox();
        pwdPanel = new javax.swing.JPanel();
        newPwdTxt = new javax.swing.JPasswordField();
        cnfNewPwdTxt = new javax.swing.JPasswordField();
        oldPwdTxt = new javax.swing.JPasswordField();
        CurPwdBar = new javax.swing.JLabel();
        CurPwdLbl = new javax.swing.JLabel();
        NewPwdBar = new javax.swing.JLabel();
        NewPwdLbl = new javax.swing.JLabel();
        CnfNewPwdBar = new javax.swing.JLabel();
        CnfPwdLbl = new javax.swing.JLabel();
        pwdCheckBox = new javax.swing.JCheckBox();
        mailTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        NameLbl = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        disCardBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        phnTxt = new javax.swing.JTextField();
        PhnLbl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        PhnLbl2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        PhnLbl1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(243, 246, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 650, 940, 10));

        resumePanel.setOpaque(false);
        resumePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("* Upload resume in within 1000kb");
        resumePanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        FilePathTxt.setEditable(false);
        resumePanel.add(FilePathTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 570, 30));

        BrowseFileBtn.setBackground(new java.awt.Color(174, 192, 236));
        BrowseFileBtn.setText("Browse File");
        BrowseFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseFileBtnActionPerformed(evt);
            }
        });
        resumePanel.add(BrowseFileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 110, 30));

        jPanel1.add(resumePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 575, 850, 60));

        PhnLbl3.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        PhnLbl3.setText("Want to change Resume");
        jPanel1.add(PhnLbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 545, -1, -1));

        resumeCheckBox.setOpaque(false);
        resumeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumeCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(resumeCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 545, 20, 20));

        pwdPanel.setOpaque(false);
        pwdPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newPwdTxt.setBackground(new java.awt.Color(173, 192, 234));
        newPwdTxt.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        newPwdTxt.setBorder(null);
        pwdPanel.add(newPwdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 63, 290, 30));

        cnfNewPwdTxt.setBackground(new java.awt.Color(173, 192, 234));
        cnfNewPwdTxt.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        cnfNewPwdTxt.setBorder(null);
        pwdPanel.add(cnfNewPwdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 290, 30));

        oldPwdTxt.setBackground(new java.awt.Color(173, 192, 234));
        oldPwdTxt.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        oldPwdTxt.setBorder(null);
        pwdPanel.add(oldPwdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 7, 290, 30));

        CurPwdBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2021-12-23 00.04.59.png"))); // NOI18N
        pwdPanel.add(CurPwdBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 0, 340, -1));

        CurPwdLbl.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        CurPwdLbl.setText("Current PassWord");
        pwdPanel.add(CurPwdLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 203, 44));

        NewPwdBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2021-12-23 00.04.59.png"))); // NOI18N
        pwdPanel.add(NewPwdBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 56, 340, -1));

        NewPwdLbl.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        NewPwdLbl.setText("New PassWord");
        pwdPanel.add(NewPwdLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 56, 203, 44));

        CnfNewPwdBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2021-12-23 00.04.59.png"))); // NOI18N
        pwdPanel.add(CnfNewPwdBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 112, 340, -1));

        CnfPwdLbl.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        CnfPwdLbl.setText("Confirm New PassWord");
        pwdPanel.add(CnfPwdLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 112, -1, 44));

        jPanel1.add(pwdPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 560, 170));

        pwdCheckBox.setOpaque(false);
        pwdCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(pwdCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 295, 20, 20));

        mailTxt.setEditable(false);
        mailTxt.setBackground(new java.awt.Color(173, 192, 234));
        mailTxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        mailTxt.setText("neelesh1210@gmail.com");
        mailTxt.setBorder(null);
        mailTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(mailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 477, 280, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2021-12-23 00.04.59.png"))); // NOI18N
        jLabel12.setText("jLabel6");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 330, -1));

        NameLbl.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        NameLbl.setText("Name :-");
        jPanel1.add(NameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        nameTxt.setEditable(false);
        nameTxt.setBackground(new java.awt.Color(173, 192, 234));
        nameTxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        nameTxt.setText("neelesh mehar");
        nameTxt.setBorder(null);
        nameTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 317, 280, 30));

        disCardBtn.setBackground(new java.awt.Color(172, 194, 236));
        disCardBtn.setText("Discard changes");
        disCardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disCardBtnActionPerformed(evt);
            }
        });
        jPanel1.add(disCardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 670, 170, 30));

        submitBtn.setBackground(new java.awt.Color(172, 194, 236));
        submitBtn.setText("Save Changes");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 670, 170, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2021-12-23 00.04.59.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 330, -1));

        phnTxt.setEditable(false);
        phnTxt.setBackground(new java.awt.Color(173, 192, 234));
        phnTxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        phnTxt.setText("8871414187");
        phnTxt.setBorder(null);
        phnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        phnTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnTxtActionPerformed(evt);
            }
        });
        jPanel1.add(phnTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 397, 280, 30));

        PhnLbl.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        PhnLbl.setText("Phone no :-");
        jPanel1.add(PhnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2021-12-23 00.04.59.png"))); // NOI18N
        jLabel11.setText("jLabel6");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 330, -1));

        PhnLbl2.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        PhnLbl2.setText("Mail Address :-");
        jPanel1.add(PhnLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 20, 240));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 970, 10));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/World-Map.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 970, 200));

        PhnLbl1.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        PhnLbl1.setText("Want to change password ");
        jPanel1.add(PhnLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/transparent logo.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 940, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void phnTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phnTxtActionPerformed

    private void pwdCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdCheckBoxActionPerformed
        // TODO add your handling code here:
       
        if(pwdCheckBox.isSelected())
        {
            pwdPanel.setVisible(true);  
        }
        else
        {
            pwdPanel.setVisible(false);
        }
    }//GEN-LAST:event_pwdCheckBoxActionPerformed

    private void resumeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumeCheckBoxActionPerformed
        // TODO add your handling code here:
        if(resumeCheckBox.isSelected())
        {
            resumePanel.setVisible(true);  
        }
        else
        {
            resumePanel.setVisible(false);
        }
    }//GEN-LAST:event_resumeCheckBoxActionPerformed

    private void BrowseFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseFileBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.setDialogTitle("Browse Files");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        int result =chooser.showOpenDialog(null);
        
        if (result == chooser.APPROVE_OPTION) 
        {   
            file=chooser.getSelectedFile();
            System.out.println(file.toString());
            String [] filename=file.toString().split("\\.");
            //System.out.println(filename[filename.length-1]);
            if(filename[filename.length-1].contains("pngjpeg"))
            {
                System.out.println(filename[filename.length-1]);
            }
            FilePathTxt.setText(file.toString().trim());
            
        } 
        else if (result == chooser.CANCEL_OPTION) 
        {
            System.out.println("Cancel was selected");
        }
    }//GEN-LAST:event_BrowseFileBtnActionPerformed

    private void disCardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disCardBtnActionPerformed
        // TODO add your handling code here:
        new ParticipantsOptionFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_disCardBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        try
        {
            int i=0,j=0;
            if(pwdCheckBox.isSelected())
            {
                if(dao.UserDao.checkOldPwd(CurrentUser.userId,oldPwdTxt.getText().trim()))
                {
                    if(newPwdTxt.getText().trim().equalsIgnoreCase(cnfNewPwdTxt.getText().trim()))
                    {
                        dao.UserDao.updatePwd(CurrentUser.userId,newPwdTxt.getText().trim());
                        JOptionPane.showMessageDialog(null,"Password Changed Successfully","Success",JOptionPane.INFORMATION_MESSAGE);
                        i=1;
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"PWD and CNF PWD are incorrect...","Error",JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Your Old Password is incorrect","Error",JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }   
            if(resumeCheckBox.isSelected())
            {
                if(FilePathTxt.getText()!="")
                {
                    dao.ParticipantsDao.updateCv(CurrentUser.userId,file);
                    JOptionPane.showMessageDialog(null,"Resumed Changed Successfully","Success",JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Please select file","Error",JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            
            if(i==1 && j==1)
            {
                JOptionPane.showMessageDialog(null,"Password & Resume updated successFully","Success",JOptionPane.INFORMATION_MESSAGE);     
            }
            else if(i==1 && j==0)
            {
                JOptionPane.showMessageDialog(null,"Password updated successFully","Success",JOptionPane.INFORMATION_MESSAGE);     
            }
            else if(i==0 && j==1)
            {
                JOptionPane.showMessageDialog(null,"Resume updated successFully","Success",JOptionPane.INFORMATION_MESSAGE);     
            }
            else
            {
               JOptionPane.showMessageDialog(null,"No Changes Done","Success",JOptionPane.INFORMATION_MESSAGE);      
            }
            
            new ParticipantsOptionFrame().setVisible(true);
            this.dispose();
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,"DB-error while Loading data","Error",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_submitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PtEditProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PtEditProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PtEditProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PtEditProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PtEditProfileFrame().setVisible(true);
            }
        });
    }
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BrowseFileBtn;
    private javax.swing.JLabel CnfNewPwdBar;
    private javax.swing.JLabel CnfPwdLbl;
    private javax.swing.JLabel CurPwdBar;
    private javax.swing.JLabel CurPwdLbl;
    private javax.swing.JTextField FilePathTxt;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JLabel NewPwdBar;
    private javax.swing.JLabel NewPwdLbl;
    private javax.swing.JLabel PhnLbl;
    private javax.swing.JLabel PhnLbl1;
    private javax.swing.JLabel PhnLbl2;
    private javax.swing.JLabel PhnLbl3;
    private javax.swing.JPasswordField cnfNewPwdTxt;
    private javax.swing.JButton disCardBtn;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField mailTxt;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JPasswordField newPwdTxt;
    private javax.swing.JPasswordField oldPwdTxt;
    private javax.swing.JTextField phnTxt;
    private javax.swing.JCheckBox pwdCheckBox;
    private javax.swing.JPanel pwdPanel;
    private javax.swing.JCheckBox resumeCheckBox;
    private javax.swing.JPanel resumePanel;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
