/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;


import dao.ParticipantsDao;
import pojo.ParticipantsPojo;
import java.io.File;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Neel_Esh
 */
public class SignUpFrame extends javax.swing.JFrame {

    /**
     * Creates new form SignUpFrame
     */
    private File file;
    public SignUpFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        reloadId();
    }
    
    void reloadId()
    {
         try
        {
            pIdLbl.setText("P-"+dao.ParticipantsDao.getParticipantsId());
        }
        catch(SQLException ex)
        {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null,"Error while uploading participants id","DataBase Error",JOptionPane.CANCEL_OPTION);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        txtPwd = new javax.swing.JPasswordField();
        txtMail = new javax.swing.JTextField();
        txtCnfPwd = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pIdLbl = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        PhnLbl3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtPhone = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        BrowseFileBtn = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        skill1Txt = new javax.swing.JTextField();
        skill3Txt = new javax.swing.JTextField();
        skill4Txt = new javax.swing.JTextField();
        qualificationTxt = new javax.swing.JTextField();
        DipperSeperator2 = new javax.swing.JSeparator();
        DipperSeperator3 = new javax.swing.JSeparator();
        createAccBtn = new javax.swing.JButton();
        backBtn1 = new javax.swing.JButton();
        DipperSeperator4 = new javax.swing.JSeparator();
        filePathTxt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        skill2Txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(243, 246, 254));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.setBackground(new java.awt.Color(173, 192, 234));
        txtName.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        txtName.setBorder(null);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 315, 410, 30));

        txtPwd.setBackground(new java.awt.Color(173, 192, 234));
        txtPwd.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        txtPwd.setBorder(null);
        jPanel1.add(txtPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 615, 400, 30));

        txtMail.setBackground(new java.awt.Color(173, 192, 234));
        txtMail.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        txtMail.setBorder(null);
        txtMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMailActionPerformed(evt);
            }
        });
        jPanel1.add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 315, 410, 30));

        txtCnfPwd.setBackground(new java.awt.Color(173, 192, 234));
        txtCnfPwd.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        txtCnfPwd.setBorder(null);
        jPanel1.add(txtCnfPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 615, 400, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 450, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 450, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 450, 40));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 610, 450, 40));

        jLabel6.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        jLabel6.setText("Email :-");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        jLabel4.setText("PassWord :-");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 110, -1));

        pIdLbl.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        pIdLbl.setText("P-101");
        jPanel1.add(pIdLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 280, -1));

        jLabel15.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        jLabel15.setText("Qualification :-");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, -1));

        jLabel16.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        jLabel16.setText("Confirm PassWord :-");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 590, -1, -1));

        jLabel19.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        jLabel19.setText("Name :-");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 420, 10));

        jLabel21.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        jLabel21.setText("Participant id :");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        PhnLbl3.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        PhnLbl3.setText("Upload Resume");
        jPanel1.add(PhnLbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, -1, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 200));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 970, 10));

        txtPhone.setBackground(new java.awt.Color(173, 192, 234));
        txtPhone.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        txtPhone.setBorder(null);
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 385, 410, 30));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 450, 40));

        BrowseFileBtn.setBackground(new java.awt.Color(174, 192, 236));
        BrowseFileBtn.setText("Browse File");
        BrowseFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseFileBtnActionPerformed(evt);
            }
        });
        jPanel1.add(BrowseFileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 380, 110, 30));

        jLabel23.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        jLabel23.setText("Mobile no :-");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        skill1Txt.setBackground(new java.awt.Color(173, 192, 234));
        skill1Txt.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        skill1Txt.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.gray));
        skill1Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skill1TxtActionPerformed(evt);
            }
        });
        jPanel1.add(skill1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 465, 190, 30));

        skill3Txt.setBackground(new java.awt.Color(173, 192, 234));
        skill3Txt.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        skill3Txt.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.gray));
        skill3Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skill3TxtActionPerformed(evt);
            }
        });
        jPanel1.add(skill3Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 465, 190, 30));

        skill4Txt.setBackground(new java.awt.Color(173, 192, 234));
        skill4Txt.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        skill4Txt.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.gray));
        skill4Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skill4TxtActionPerformed(evt);
            }
        });
        jPanel1.add(skill4Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 465, 190, 30));

        qualificationTxt.setBackground(new java.awt.Color(173, 192, 234));
        qualificationTxt.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        qualificationTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.gray));
        qualificationTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qualificationTxtActionPerformed(evt);
            }
        });
        jPanel1.add(qualificationTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 950, 30));
        jPanel1.add(DipperSeperator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, 950, 20));
        jPanel1.add(DipperSeperator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 950, 20));

        createAccBtn.setBackground(new java.awt.Color(173, 192, 234));
        createAccBtn.setText("Create Account");
        createAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccBtnActionPerformed(evt);
            }
        });
        jPanel1.add(createAccBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 670, 220, 30));

        backBtn1.setBackground(new java.awt.Color(173, 192, 234));
        backBtn1.setText("Login Page");
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 670, 160, 30));
        jPanel1.add(DipperSeperator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 950, 20));

        filePathTxt.setEditable(false);
        filePathTxt.setBackground(new java.awt.Color(173, 192, 234));
        filePathTxt.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        filePathTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.gray));
        filePathTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filePathTxtActionPerformed(evt);
            }
        });
        jPanel1.add(filePathTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 330, 30));

        jLabel18.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        jLabel18.setText("Skills -");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        skill2Txt.setBackground(new java.awt.Color(173, 192, 234));
        skill2Txt.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        skill2Txt.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.gray));
        skill2Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skill2TxtActionPerformed(evt);
            }
        });
        jPanel1.add(skill2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 465, 190, 30));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/World-Map.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 970, 200));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/transparent logo.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void BrowseFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseFileBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.setDialogTitle("Browse Files");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int result =chooser.showOpenDialog(null);

        if (result == chooser.APPROVE_OPTION)
        {
            file=chooser.getSelectedFile();
            System.out.println(file.toString());
            System.out.println(file.getName());
            
            //System.out.println(filename[filename.length-1]);
            
            
            filePathTxt.setText(file.toString().trim());

        }
        else if (result == chooser.CANCEL_OPTION)
        {
            System.out.println("Cancel was selected");
        }
    }//GEN-LAST:event_BrowseFileBtnActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void skill1TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skill1TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_skill1TxtActionPerformed

    private void skill3TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skill3TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_skill3TxtActionPerformed

    private void skill4TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skill4TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_skill4TxtActionPerformed

    private void qualificationTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qualificationTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qualificationTxtActionPerformed

    private void createAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccBtnActionPerformed
        // TODO add your handling code here:
        if(validateInputs())
        {
        
           
            ParticipantsPojo pt=new ParticipantsPojo();
            pt.setpId(pIdLbl.getText().trim());
            pt.setUserId(txtMail.getText().toUpperCase().trim());
            pt.setName(txtName.getText().trim());
            pt.setPhone(txtPhone.getText().trim());
            pt.setResume(new File(filePathTxt.getText().trim()));
            pt.setSkills(skill1Txt.getText().trim()+","+skill2Txt.getText().trim()+","+skill3Txt.getText().trim()+","+skill4Txt.getText().trim());
            pt.setQualifications(qualificationTxt.getText().trim());
            
            if(pwdInputs())
            {
                pt.setPassword(txtPwd.getText().trim());
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Password & Confrim Password aren't same !!!","Warning",JOptionPane.INFORMATION_MESSAGE);
                return; 
            }
            
            if(ParticipantsDao.addNewParticipants(pt))
            {
                JOptionPane.showMessageDialog(null,"Participants Added Succefully","Success",JOptionPane.INFORMATION_MESSAGE);
                txtMail.setText("");
                txtName.setText("");
                txtPhone.setText("");
                filePathTxt.setText("");
                skill1Txt.setText("");
                skill2Txt.setText("");
                skill3Txt.setText("");
                skill4Txt.setText("");
                qualificationTxt.setText("");
                txtPwd.setText("");
                txtCnfPwd.setText("");
                reloadId();
                return;
            }
            else
            {
                JOptionPane.showMessageDialog(null,"DB-error while adding particpant","Error",JOptionPane.ERROR_MESSAGE);
                return;
            }
        
        
            
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please fill all fields","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_createAccBtnActionPerformed

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtn1ActionPerformed

    private void filePathTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filePathTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filePathTxtActionPerformed

    private void skill2TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skill2TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_skill2TxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpFrame().setVisible(true);
            }
        });
    }
    
     public boolean validateInputs()
    {
        if(txtName.getText().isEmpty() || txtMail.getText().isEmpty() || txtPhone.getText().isEmpty() || txtPwd.getText().isEmpty() || txtCnfPwd.getText().isEmpty()
 || skill1Txt.getText().isEmpty() || qualificationTxt.getText().isEmpty()|| skill3Txt.getText().isEmpty()|| skill4Txt.getText().isEmpty()|| filePathTxt.getText().isEmpty())
             return false;
        return true;
    }
    
    public boolean pwdInputs()
    {
        if(txtPwd.getText().trim().equalsIgnoreCase(txtCnfPwd.getText().trim()))
             return true;
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BrowseFileBtn;
    private javax.swing.JSeparator DipperSeperator2;
    private javax.swing.JSeparator DipperSeperator3;
    private javax.swing.JSeparator DipperSeperator4;
    private javax.swing.JLabel PhnLbl3;
    private javax.swing.JButton backBtn1;
    private javax.swing.JButton createAccBtn;
    private javax.swing.JTextField filePathTxt;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel pIdLbl;
    private javax.swing.JTextField qualificationTxt;
    private javax.swing.JTextField skill1Txt;
    private javax.swing.JTextField skill2Txt;
    private javax.swing.JTextField skill3Txt;
    private javax.swing.JTextField skill4Txt;
    private javax.swing.JPasswordField txtCnfPwd;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JPasswordField txtPwd;
    // End of variables declaration//GEN-END:variables
}
